name = "diliinfo"
main = "index.ts"
compatibility_date = "2024-01-30"

d1_databases = [
  { binding = "DB", database_name = "diliinfo-db", database_id = "<YOUR_DB_ID>" }
]

#开发环境绑定
[env.dev]
route = ""

[env.production]
route = "api.diliinfo.com/*" 