name: Deploy Frontend and Backend

on:
  push:
    branches: [main]          # main 分支有变动即触发

# 给予 workflow 中的 GITHUB_TOKEN 对仓库内容拥有写权限，以便推送 gh-pages
permissions:
  contents: write

jobs:
  # 部署后端到 Cloudflare Workers
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: workers-backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: workers-backend
          command: deploy --env production

  # 部署前端到 GitHub Pages
  build-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend  # 等待后端部署完成
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Copy 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/web/dist
          publish_branch: gh-pages